# Generated by Django 5.0.14 on 2025-04-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_rename_created_at_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
