# Generated by Django 5.0.14 on 2025-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_meetingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingschedule',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
