# Generated by Django 5.0.14 on 2025-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='expertise',
            field=models.CharField(choices=[('criminal', 'Criminal Law'), ('civil', 'Civil Law'), ('family', 'Family Law'), ('property', 'Property Law'), ('corporate', 'Corporate Law')], max_length=100),
        ),
    ]
