# Generated by Django 5.0.14 on 2025-04-19 15:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_lawyerprofile_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_picture_path),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_picture_path),
        ),
    ]
